server:
  port: 9999
#logging:
#  level:
#    org.springframework: debug
#    org.springframework.boot.autoconfigure: error
#    org.springframework.web: info
spring:
  devtools:
    restart:
      enabled: false
  #连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tqt?characterEncoding=utf-8&useSSL=true
    username: root
    password: root
#    url: jdbc:mysql://39.108.56.138:3306/tqt?characterEncoding=utf-8&useSSL=true
#    username: root
#    password: qweasdzxc!@#
    #类型
    type: com.alibaba.druid.pool.DruidDataSource
  #JPA
  jpa:
    hibernate:
      #是否自动创建ddl
      ddl-auto: none
      #是否控制台输出sql
      naming:
        physical-strategy: com.coachtam.tqt.config.hibernate.MySQLUpperCaseStrategy
    #数据库
    database: mysql
    properties:
      #hibernate 其它属性，可以用来配置其它hibernate配置
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        show_sql: false
    #是否在视图层也打开session(open session in view)
    open-in-view: true
  #ACTIVITI
  activiti:
    database-schema-update: true
    check-process-definitions: true
    history-level: full
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
tqt:
  global:
    adminRoles: #管理员角色
      - 管理员
      - 老师
  security:
    oauth2:
      storeType: jwt #或者jwt
      jwtSigningKey: tqt
      clients[0]:
        clientId: tqt
        clientSecret: tqt
      clients[1]:
        clientId: tqt1
        clientSecret: tqt1
  upload:
#    uploadPath: /Users/macbook/Desktop/tqt/src/tqt-api/target/classes/static
#    accessPath: http://localhost:9999
    uploadPath: /usr/local/nginx/html/admin
    accessPath: http://tqt2020.oss-cn-chengdu.aliyuncs.com
  jwt:
    paramName: access_token
    secret: ego@Login(Auth}*^31)&ego% # 登录校验的密钥
    priKeyPath: /Users/macbook/rsa/rsa.pri # 私钥地址
    pubKeyPath: /Users/macbook/rsa/rsa.pub # 公钥地址
    expire: 1 # 过期时间,单位分钟
